#
# Module manifest for module 'AsciiText'
#
# Generated by: Michael Tartaggia
#
# Generated on: 2024-10-05
#
@{
	ModuleVersion = '1.0.0'
	Description = 'Generates Ascii Text Art'
	GUID = 'e727ded6-207a-4f91-b4e9-1d30e2514cba'
	Author = 'Michael Tartaggia'
	ProcessorArchitecture = 'None'
	FunctionsToExport = 'Show-Font', 'Get-AsciiText', 'Write-AsciiText', 'Get-Font'
	CmdletsToExport = '*' 
	VariablesToExport = '*'
	AliasesToExport = '*'
	FileList = 'AsciiText.psm1', 'AsciiText.psd1', '3DDiagonal.psf', 'Arrows.psf', 'ASCIINewRoman.psf', 'Avatar.psf', 'Big.psf', 'Caligraphy.psf', 'Chunky.psf', 'Contessa.psf', 'Digital.psf', 'Doom.psf', 'EftiFont.psf', 'EftiRobot,
 Graceful.psf', 'Graffiti.psf', 'Impossible.psf', 'LilDevil.psf', 'Merlin1.psf', 'Modular.psf', 'Ogre.psf', 'Pepper.psf', 'Rectangles.psf', 'SmallShadow.psf', 'Stop.psf'


PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('ASCII', 'Text', 'Art', 'Font','Write')


        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/MrMichaelST/AsciiText'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '* Inital Release'



    }

}

}
